# Automatically generate documentation and commit back into branch
name: Auto Document

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup GIT
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
      - name: Checkout documentation branch
        uses: actions/checkout@v1
        with:
          ref: documentation
          clean: false
      - name: Merge master to documentation
        run: git merge master
      - name: Delete old docs
        run: rm -rf docs
      - name: Remove old docs from git
        run: git rm docs -rf
      - name: Install Node packages
        run: npm install
      - name: Document
        run: npm run document
      - name: Add generated docs
        run: git add docs/*
      - name: Commit
        run: git commit -m "Auto-document"
      - name: Push to docs branch
        run: git push
