# Automatically generate documentation and commit back into branch
name: Auto Document

on:
  push:
    branches: [ master ]

jobs:
  document:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: Document
        run: npm run document
      - name: Add & Commit
        uses: EndBug/add-and-commit@v5.1.0
        with:
          add: ./documentation/*
          message: Auto-document
